sudo: required
dist: focal
language: node_js
cache:
  npm: false
addons:
  chrome: stable
node_js:
  - "10"
  - "11"
  - "12"
  - "13"

services:
  - docker

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'

install:
  - npm install

before_install:
  - ./scripts/start-server.sh

before_script:
  - make lint

script: 
  - ./run-tests.sh